-- Insert into assets
INSERT INTO
    assets (asset_key, asset)
VALUES
    (
        'ALEXSTRAZA',
        '../../public/assets/images/cards/alexstraza.webp'
    ) ON CONFLICT (asset_key) DO NOTHING;

-- Insert into types
INSERT INTO
    types (type)
VALUES
    ('MINION') ON CONFLICT (type) DO NOTHING;

-- Insert into battlecry_types
INSERT INTO
    battlecry_types (type)
VALUES
    ('HEAL'),
    ('DAMAGE') ON CONFLICT (type) DO NOTHING;

-- Insert into battlecry_targets
INSERT INTO
    battlecry_targets (target)
VALUES
    ('ANY'),
    ('ENEMY'),
    ('FRIENDLY'),
    ('RANDOM_ENEMY'),
    ('RANDOM_FRIENDLY'),
    ('RANDOM_ENEMY_MINION'),
    ('RANDOM_FRIENDLY_MINION'),
    ('ENEMY_HERO'),
    ('FRIENDLY_HERO') ON CONFLICT (target) DO NOTHING;

-- Insert cards and their battlecries
WITH asset_id AS (
    SELECT
        id
    FROM
        assets
    WHERE
        asset_key = 'ALEXSTRAZA'
),
type_id AS (
    SELECT
        id
    FROM
        types
    WHERE
        type = 'MINION'
),
battlecry_type_damage AS (
    SELECT
        id
    FROM
        battlecry_types
    WHERE
        type = 'DAMAGE'
),
battlecry_type_heal AS (
    SELECT
        id
    FROM
        battlecry_types
    WHERE
        type = 'HEAL'
),
battlecry_target_enemy_hero AS (
    SELECT
        id
    FROM
        battlecry_targets
    WHERE
        target = 'ENEMY_HERO'
),
battlecry_target_random_enemy AS (
    SELECT
        id
    FROM
        battlecry_targets
    WHERE
        target = 'RANDOM_ENEMY'
),
battlecry_target_random_friendly_minion AS (
    SELECT
        id
    FROM
        battlecry_targets
    WHERE
        target = 'RANDOM_FRIENDLY_MINION'
),
battlecry_target_random_enemy_minion AS (
    SELECT
        id
    FROM
        battlecry_targets
    WHERE
        target = 'RANDOM_ENEMY_MINION'
),
battlecry_target_friendly_hero AS (
    SELECT
        id
    FROM
        battlecry_targets
    WHERE
        target = 'FRIENDLY_HERO'
),
battlecry_target_friendly AS (
    SELECT
        id
    FROM
        battlecry_targets
    WHERE
        target = 'FRIENDLY'
),
battlecry_target_any AS (
    SELECT
        id
    FROM
        battlecry_targets
    WHERE
        target = 'ANY'
) -- Insert battlecries and cards
INSERT INTO
    battlecries (amount, battlecry_type_id, battlecry_target_id)
VALUES
    (
        2,
        (
            SELECT
                id
            FROM
                battlecry_type_damage
        ),
        (
            SELECT
                id
            FROM
                battlecry_target_enemy_hero
        )
    ),
    (
        2,
        (
            SELECT
                id
            FROM
                battlecry_type_damage
        ),
        (
            SELECT
                id
            FROM
                battlecry_target_random_enemy
        )
    ),
    (
        2,
        (
            SELECT
                id
            FROM
                battlecry_type_heal
        ),
        (
            SELECT
                id
            FROM
                battlecry_target_random_friendly_minion
        )
    ),
    (
        2,
        (
            SELECT
                id
            FROM
                battlecry_type_damage
        ),
        (
            SELECT
                id
            FROM
                battlecry_target_random_enemy_minion
        )
    ),
    (
        3,
        (
            SELECT
                id
            FROM
                battlecry_type_heal
        ),
        (
            SELECT
                id
            FROM
                battlecry_target_friendly_hero
        )
    ),
    (
        3,
        (
            SELECT
                id
            FROM
                battlecry_type_damage
        ),
        (
            SELECT
                id
            FROM
                battlecry_target_any
        )
    ),
    (
        3,
        (
            SELECT
                id
            FROM
                battlecry_type_heal
        ),
        (
            SELECT
                id
            FROM
                battlecry_target_friendly
        )
    ),
    (
        4,
        (
            SELECT
                id
            FROM
                battlecry_type_heal
        ),
        (
            SELECT
                id
            FROM
                battlecry_target_random_friendly
        )
    ),
    (
        4,
        (
            SELECT
                id
            FROM
                battlecry_type_damage
        ),
        (
            SELECT
                id
            FROM
                battlecry_target_any
        )
    ),
    (
        5,
        (
            SELECT
                id
            FROM
                battlecry_type_damage
        ),
        (
            SELECT
                id
            FROM
                battlecry_target_random_enemy_minion
        )
    ),
    (
        4,
        (
            SELECT
                id
            FROM
                battlecry_type_damage
        ),
        (
            SELECT
                id
            FROM
                battlecry_target_enemy_hero
        )
    ) ON CONFLICT DO NOTHING;

-- Insert cards
INSERT INTO
    cards (
        id,
        attack,
        health,
        cost,
        text,
        battlecry_id,
        asset_id,
        type_id
    )
VALUES
    (
        1,
        1,
        2,
        1,
        '[i]Battlecry:[/i] Deal 2 damage to the enemy hero.',
        1,
        (
            SELECT
                id
            FROM
                asset_id
        ),
        (
            SELECT
                id
            FROM
                type_id
        )
    ),
    (
        2,
        3,
        3,
        2,
        '',
        NULL,
        (
            SELECT
                id
            FROM
                asset_id
        ),
        (
            SELECT
                id
            FROM
                type_id
        )
    ),
    (
        3,
        2,
        2,
        2,
        '[i]Battlecry:[/i] Deal 2 damage to a random enemy.',
        2,
        (
            SELECT
                id
            FROM
                asset_id
        ),
        (
            SELECT
                id
            FROM
                type_id
        )
    ),
    (
        4,
        1,
        3,
        1,
        '[i]Battlecry:[/i] Heal 2 health to a random friendly minion.',
        3,
        (
            SELECT
                id
            FROM
                asset_id
        ),
        (
            SELECT
                id
            FROM
                type_id
        )
    ),
    (
        5,
        2,
        4,
        2,
        '[i]Battlecry:[/i] Deal 2 damage to a random enemy minion.',
        4,
        (
            SELECT
                id
            FROM
                asset_id
        ),
        (
            SELECT
                id
            FROM
                type_id
        )
    ),
    (
        6,
        0,
        4,
        1,
        '',
        NULL,
        (
            SELECT
                id
            FROM
                asset_id
        ),
        (
            SELECT
                id
            FROM
                type_id
        )
    ),
    (
        7,
        3,
        3,
        3,
        '[i]Battlecry:[/i] Heal 3 health to your hero.',
        5,
        (
            SELECT
                id
            FROM
                asset_id
        ),
        (
            SELECT
                id
            FROM
                type_id
        )
    ),
    (
        8,
        1,
        5,
        2,
        '',
        NULL,
        (
            SELECT
                id
            FROM
                asset_id
        ),
        (
            SELECT
                id
            FROM
                type_id
        )
    ),
    (
        9,
        4,
        3,
        4,
        '[i]Battlecry:[/i] Deal 3 damage.',
        6,
        (
            SELECT
                id
            FROM
                asset_id
        ),
        (
            SELECT
                id
            FROM
                type_id
        )
    ),
    (
        10,
        2,
        2,
        3,
        '[i]Battlecry:[/i] Heal 3 health to a friendly character.',
        7,
        (
            SELECT
                id
            FROM
                asset_id
        ),
        (
            SELECT
                id
            FROM
                type_id
        )
    ),
    (
        11,
        6,
        6,
        5,
        '',
        NULL,
        (
            SELECT
                id
            FROM
                asset_id
        ),
        (
            SELECT
                id
            FROM
                type_id
        )
    ),
    (
        12,
        4,
        4,
        4,
        '[i]Battlecry:[/i] Heal 4 health to a random friendly character.',
        8,
        (
            SELECT
                id
            FROM
                asset_id
        ),
        (
            SELECT
                id
            FROM
                type_id
        )
    ),
    (
        13,
        3,
        3,
        3,
        '',
        NULL,
        (
            SELECT
                id
            FROM
                asset_id
        ),
        (
            SELECT
                id
            FROM
                type_id
        )
    ),
    (
        14,
        5,
        5,
        5,
        '[i]Battlecry:[/i] Deal 3 damage to an enemy.',
        9,
        (
            SELECT
                id
            FROM
                asset_id
        ),
        (
            SELECT
                id
            FROM
                type_id
        )
    ),
    (
        15,
        1,
        1,
        1,
        '',
        NULL,
        (
            SELECT
                id
            FROM
                asset_id
        ),
        (
            SELECT
                id
            FROM
                type_id
        )
    ),
    (
        16,
        2,
        2,
        2,
        '[i]Battlecry:[/i] Deal 2 damage to the enemy hero.',
        1,
        (
            SELECT
                id
            FROM
                asset_id
        ),
        (
            SELECT
                id
            FROM
                type_id
        )
    ),
    (
        17,
        3,
        4,
        3,
        '[i]Battlecry:[/i] Heal 2 health.',
        10,
        (
            SELECT
                id
            FROM
                asset_id
        ),
        (
            SELECT
                id
            FROM
                type_id
        )
    ),
    (
        18,
        4,
        5,
        4,
        '[i]Battlecry:[/i] Deal 3 damage to a random enemy minion.',
        11,
        (
            SELECT
                id
            FROM
                asset_id
        ),
        (
            SELECT
                id
            FROM
                type_id
        )
    ),
    (
        19,
        6,
        4,
        6,
        '',
        NULL,
        (
            SELECT
                id
            FROM
                asset_id
        ),
        (
            SELECT
                id
            FROM
                type_id
        )
    ),
    (
        20,
        3,
        3,
        3,
        '[i]Battlecry:[/i] Heal 4 health to your hero.',
        5,
        (
            SELECT
                id
            FROM
                asset_id
        ),
        (
            SELECT
                id
            FROM
                type_id
        )
    ),
    (
        21,
        5,
        4,
        5,
        '[i]Battlecry:[/i] Deal 4 damage to a random enemy.',
        11,
        (
            SELECT
                id
            FROM
                asset_id
        ),
        (
            SELECT
                id
            FROM
                type_id
        )
    ),
    (
        22,
        1,
        1,
        1,
        '[i]Battlecry:[/i] Heal 1 health to a friendly character.',
        7,
        (
            SELECT
                id
            FROM
                asset_id
        ),
        (
            SELECT
                id
            FROM
                type_id
        )
    ),
    (
        23,
        2,
        3,
        2,
        '[i]Battlecry:[/i] Deal 2 damage to an enemy.',
        9,
        (
            SELECT
                id
            FROM
                asset_id
        ),
        (
            SELECT
                id
            FROM
                type_id
        )
    ),
    (
        24,
        4,
        4,
        4,
        '',
        NULL,
        (
            SELECT
                id
            FROM
                asset_id
        ),
        (
            SELECT
                id
            FROM
                type_id
        )
    ),
    (
        25,
        3,
        2,
        3,
        '[i]Battlecry:[/i] Heal 3 health to a random friendly character.',
        8,
        (
            SELECT
                id
            FROM
                asset_id
        ),
        (
            SELECT
                id
            FROM
                type_id
        )
    ),
    (
        26,
        4,
        5,
        4,
        '[i]Battlecry:[/i] Deal 4 damage.',
        10,
        (
            SELECT
                id
            FROM
                asset_id
        ),
        (
            SELECT
                id
            FROM
                type_id
        )
    ),
    (
        27,
        2,
        6,
        3,
        '',
        NULL,
        (
            SELECT
                id
            FROM
                asset_id
        ),
        (
            SELECT
                id
            FROM
                type_id
        )
    ),
    (
        28,
        5,
        6,
        6,
        '[i]Battlecry:[/i] Deal 5 damage to a random enemy minion.',
        11,
        (
            SELECT
                id
            FROM
                asset_id
        ),
        (
            SELECT
                id
            FROM
                type_id
        )
    ),
    (
        29,
        1,
        1,
        1,
        '',
        NULL,
        (
            SELECT
                id
            FROM
                asset_id
        ),
        (
            SELECT
                id
            FROM
                type_id
        )
    ),
    (
        30,
        4,
        4,
        4,
        '[i]Battlecry:[/i] Deal 4 damage to the enemy hero.',
        1,
        (
            SELECT
                id
            FROM
                asset_id
        ),
        (
            SELECT
                id
            FROM
                type_id
        )
    );