export const TARGET_KEYS = Object.freeze({
  PLAYER: 'PLAYER',
  OPPONENT: 'OPPONENT',
})
export type TargetKeys = keyof typeof TARGET_KEYS

export const BATTLE_TARGET_KEYS = Object.freeze({
  ATTACKER: 'ATTACKER',
  DEFENDER: 'DEFENDER',
})
export type BattleTargetKeys = keyof typeof BATTLE_TARGET_KEYS

export const BATTLE_STATES = Object.freeze({
  PLAYER_TURN: 'PLAYER_TURN',
  AFTER_BATTLE_CHECK: 'AFTER_BATTLE_CHECK',
  AFTER_EFFECT_CHECK: 'AFTER_EFFECT_CHECK',
  OPPONENT_TURN: 'OPPONENT_TURN',
  GAME_END: 'GAME_END',
  PLAYER_PLAY_CARD: 'PLAYER_PLAY_CARD',
  PLAYER_CHOOSE_TARGET: 'PLAYER_CHOOSE_TARGET',
  PLAYER_TARGET_CHOSEN: 'PLAYER_TARGET_CHOSEN',
  OPPONENT_PLAY_CARD: 'OPPONENT_PLAY_CARD',
  PLAYER_TURN_START: 'PLAYER_TURN_START',
  OPPONENT_TURN_START: 'OPPONENT_TURN_START',
  PLAYER_TURN_END: 'PLAYER_TURN_END',
  OPPONENT_TURN_END: 'OPPONENT_TURN_END',
  PLAYER_DRAW_CARD: 'PLAYER_DRAW_CARD',
  OPPONENT_DRAW_CARD: 'OPPONENT_DRAW_CARD',
  ATTACKER_MINION_CHOSEN: 'ATTACKER_MINION_CHOSEN',
  DEFENDER_MINION_CHOSEN: 'DEFENDER_MINION_CHOSEN',
  MINION_BATTLE: 'MINION_BATTLE',
})
export type BattleStates = keyof typeof BATTLE_STATES

export const WARNING_KEYS = Object.freeze({
  CANT_PLAY: "YOU CAN'T PLAY THIS RIGHT NOW",
  SUMMONING_SICK: 'THIS MINION NEEDS A TURN TO BE READY',
  ALREADY_ATTACKED: 'THIS MINION ALREADY ATTACKED',
  NOT_VALID_TARGET: 'THIS IS NOT A VALID TARGET',
})
export type WarningKeys = (typeof WARNING_KEYS)[keyof typeof WARNING_KEYS]
